platform :ios, '10.0'

use_frameworks!

def shared_pods
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'SDWebImage/WebP'
    pod 'SwiftyJSON'
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'RxDataSources'
    
    pod 'Swinject'
    
    pod 'Cartography'
end

target 'Countries-api' do
    shared_pods
end
